version: '3.7'
services:
  mysql_db_container:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: renjinduo 
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
  nuxt_app_container:
    container_name: nuxt_app
    restart: always
    #构建容器
    build:
      context: .
      # 自动输入Y防止造成编译卡死
      args:
        - "-y"
    ports:
      - "3004:3000"
    environment:
      DATABASE_URL: mysql://root:renjinduo@mysql_db_container:3306/test
      # NUXT_BASE_URL: https://jsonplaceholder.typicode.com
      # JSON_SECRET: thisisjsonsecret
    command: >
      /bin/sh -c 'npm run migrate && npm run build && npm start'
    depends_on:
      mysql_db_container:
        condition: service_healthy
volumes:
  mysql_db_data_container:
